"""Blocked-task signal plumbing.

A task agent that cannot complete its task for out-of-scope reasons signals
BLOCKED by running a small shell script ola provisions into its worktree
(``<worktree>/.ola/bin/ola-blocked``). The script writes the reason to a
marker file under the *agent folder* (``<folder>/.ola/blocked/<task_id>.reason``)
so the record survives worktree cleanup; the scheduler reads it after the
worker exits and routes the task to the janitor instead of retrying it.

The marker payload is the raw reason string (plain text) — composing JSON
from ``sh`` invites quoting bugs. The harness builds the structured
:class:`BlockedRecord` from the filename (task_id) and mtime (timestamp).
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

logger = logging.getLogger(__name__)

_BLOCKED_SUBDIR = Path(".ola") / "blocked"
_SCRIPT_SUBDIR = Path(".ola") / "bin"

_SCRIPT_TEMPLATE = """\
#!/bin/sh
# Generated by ola for task {task_id}. Run this if the task is blocked on
# something out of scope, then stop working immediately.
reason=""
if [ "$1" = "--reason" ]; then
    reason="$2"
fi
mkdir -p "{blocked_dir}"
printf '%s' "$reason" > "{marker_path}"
echo "ola: task {task_id} recorded as BLOCKED. End your session now."
"""


@dataclass(frozen=True)
class BlockedRecord:
    """A task's self-reported blockage: who, why, and when."""

    task_id: str
    reason: str
    ts: str  # ISO-8601 UTC, derived from the marker file's mtime


def _marker_path(folder: Path, task_id: str) -> Path:
    return Path(folder) / _BLOCKED_SUBDIR / f"{task_id}.reason"


def provision_blocked_script(worktree_path: Path, folder: Path, task_id: str) -> Path:
    """Write the ``ola-blocked`` escape-hatch script into *worktree_path*.

    The agent-folder marker path and task_id are baked in at provisioning
    time, so the script needs no arguments beyond ``--reason``. The agent
    folder and the worktree share a filesystem view (same reasoning as the
    ``gitdir:`` pointer in :mod:`ola.worktree`), so an absolute path works
    both on the host and inside the sandbox.
    """
    folder = Path(folder).resolve()
    marker = _marker_path(folder, task_id)
    script = Path(worktree_path) / _SCRIPT_SUBDIR / "ola-blocked"
    script.parent.mkdir(parents=True, exist_ok=True)
    script.write_text(
        _SCRIPT_TEMPLATE.format(
            task_id=task_id,
            blocked_dir=str(marker.parent),
            marker_path=str(marker),
        )
    )
    script.chmod(0o755)
    return script


def read_blocked_record(folder: Path, task_id: str) -> BlockedRecord | None:
    """Return the blocked record for *task_id*, or ``None`` if no marker exists."""
    marker = _marker_path(folder, task_id)
    try:
        reason = marker.read_text().strip()
        mtime = marker.stat().st_mtime
    except FileNotFoundError:
        return None
    ts = datetime.fromtimestamp(mtime, tz=timezone.utc).isoformat(
        timespec="milliseconds"
    )
    return BlockedRecord(task_id=task_id, reason=reason, ts=ts)


def clear_blocked_record(folder: Path, task_id: str) -> None:
    """Remove the marker for *task_id*; a no-op when none exists.

    Called at dispatch time so a stale marker from a prior attempt cannot
    poison a fresh run, and defensively on completion (tick wins).
    """
    _marker_path(folder, task_id).unlink(missing_ok=True)
